/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Demot.BaiMot;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author nguyenmanh
 */
public class frmNhapThongTinSV extends javax.swing.JFrame {

    /**
     * Creates new form frmNhapThongTinSV
     */
    public frmNhapThongTinSV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gioiTinh = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lbl_hoTen = new javax.swing.JLabel();
        lbl_ngaySinh = new javax.swing.JLabel();
        lbl_gioiTinh = new javax.swing.JLabel();
        lbl_diaChi = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_diemTongKet = new javax.swing.JLabel();
        lbl_maSV = new javax.swing.JLabel();
        txt_maSV = new javax.swing.JTextField();
        txt_hoTen = new javax.swing.JTextField();
        txt_ngaySinh = new javax.swing.JTextField();
        rd_nam = new javax.swing.JRadioButton();
        rd_nu = new javax.swing.JRadioButton();
        rd_khac = new javax.swing.JRadioButton();
        txt_diaChi = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_diemTongKet = new javax.swing.JTextField();
        btn_themSinhVien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhap thong tin sinh vien");

        lbl_hoTen.setText("Ho ten:");

        lbl_ngaySinh.setText("Ngay sinh:");

        lbl_gioiTinh.setText("Gioi tinh:");

        lbl_diaChi.setText("Dia chi:");

        lbl_email.setText("Email:");

        lbl_diemTongKet.setText("Diem tong ket:");

        lbl_maSV.setText("Ma sv:");

        gioiTinh.add(rd_nam);
        rd_nam.setText("Nam");

        gioiTinh.add(rd_nu);
        rd_nu.setText("Nu");

        gioiTinh.add(rd_khac);
        rd_khac.setText("khac");

        btn_themSinhVien.setText("Them sinh vien");
        btn_themSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themSinhVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ngaySinh)
                            .addComponent(lbl_gioiTinh)
                            .addComponent(lbl_diaChi)
                            .addComponent(lbl_email)
                            .addComponent(lbl_diemTongKet)
                            .addComponent(lbl_hoTen)
                            .addComponent(lbl_maSV))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(txt_maSV)
                            .addComponent(txt_hoTen)
                            .addComponent(txt_ngaySinh)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rd_nam)
                                .addGap(18, 18, 18)
                                .addComponent(rd_nu)
                                .addGap(36, 36, 36)
                                .addComponent(rd_khac))
                            .addComponent(txt_diaChi)
                            .addComponent(txt_email)
                            .addComponent(txt_diemTongKet, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(btn_themSinhVien)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_maSV)
                    .addComponent(txt_maSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_hoTen)
                    .addComponent(txt_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ngaySinh)
                    .addComponent(txt_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_gioiTinh)
                    .addComponent(rd_nam)
                    .addComponent(rd_nu)
                    .addComponent(rd_khac))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_diaChi)
                    .addComponent(txt_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_email)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_diemTongKet)
                    .addComponent(txt_diemTongKet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_themSinhVien)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themSinhVienActionPerformed
        Student st = new Student();
        
        String hoten = this.txt_hoTen.getText();
        String ngaysinh = this.txt_ngaySinh.getText();
        String diachi = this.txt_diaChi.getText();
        String email = this.txt_email.getText();
        float diemtongket = Float.parseFloat(this.txt_diemTongKet.getText());
        String gioitinh = "";
        String masv = this.txt_maSV.getText();
        
        if(this.rd_nam.isSelected()){
            gioitinh = "nam";
        }else if(this.rd_nu.isSelected()){
            gioitinh = "nu";
        }else if(this.rd_khac.isSelected()){
            gioitinh = "khac";
        }
        
        st.setHoTen(hoten);
        st.setEmail(email);
        st.setNgaySinh(ngaysinh);
        st.setDiaChi(diachi);
        st.setDiemTongKet(diemtongket);
        st.setGioiTinh(gioitinh);
        st.setMaSV(masv);

        
        st.hienThiThongTin();
        
        this.save(st);
    }//GEN-LAST:event_btn_themSinhVienActionPerformed
    
    
    public void save(Student st){
        BufferedWriter bfw = null;
        FileWriter fw = null;
        File f = new File("sinhvienDe1.dat");
        
        try {
            fw = new FileWriter(f);
            bfw = new BufferedWriter(fw);
            
            bfw.write(st.getMaSV() + "\t" + st.getHoTen() + "\t" + st.getGioiTinh() + "\t" + st.getNgaySinh() + "\t" + st.getEmail() + "\t" + st.getDiemTongKet() + "\t" + st.getDiaChi());
            
            bfw.close();
        } catch (IOException ex) {
            Logger.getLogger(frmNhapThongTinSV.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNhapThongTinSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNhapThongTinSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNhapThongTinSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNhapThongTinSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNhapThongTinSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_themSinhVien;
    private javax.swing.ButtonGroup gioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_diaChi;
    private javax.swing.JLabel lbl_diemTongKet;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_gioiTinh;
    private javax.swing.JLabel lbl_hoTen;
    private javax.swing.JLabel lbl_maSV;
    private javax.swing.JLabel lbl_ngaySinh;
    private javax.swing.JRadioButton rd_khac;
    private javax.swing.JRadioButton rd_nam;
    private javax.swing.JRadioButton rd_nu;
    private javax.swing.JTextField txt_diaChi;
    private javax.swing.JTextField txt_diemTongKet;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_hoTen;
    private javax.swing.JTextField txt_maSV;
    private javax.swing.JTextField txt_ngaySinh;
    // End of variables declaration//GEN-END:variables
}
